spring.application.name=multitenant

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/multitenant}
spring.datasource.username=${DB_USERNAME:multitenant}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.default-schema=${APP_TENANCY_DEFAULT_TENANT:public}
spring.flyway.schemas=${APP_TENANCY_DEFAULT_TENANT:public}
spring.flyway.create-schemas=true
spring.flyway.locations=classpath:db/migration

app.tenancy.header-name=X-Tenant-ID
app.tenancy.default-tenant=${APP_TENANCY_DEFAULT_TENANT:public}
app.tenancy.tenant-migration-location=classpath:db/tenant